apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka-headless-service
  namespace: datahangar-stack
spec:
  ports:
    - port: 9092
      name: broker
    - port: 9093
      name: broker-internal
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka-service
  namespace: datahangar-stack
spec:
  ports:
    - port: 9092
      name: broker
    - port: 9093
      name: broker-internal
  selector:
    app: kafka
