apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfacctd-workers
  namespace: datahangar-stack
  labels:
    app: nfacctd
spec:
  selector:
    matchLabels:
      app: nfacctd
  replicas: 1
  template:
    metadata:
      labels:
        app: nfacctd
    spec:
      initContainers:
        - name: nfacctd-conf-generator
          image: ghcr.io/datahangar/init-conf-gen:0.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka
                  key: username
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka
                  key: password
          command: ["sh", "-c", "python3 /tmp/pmacct/gen_nfacctd_conf.py"]
          volumeMounts:
            - name: datahangar-config-volume
              mountPath: /etc/datahangar
              readOnly: true
            - name: nfacctd-config-volume
              mountPath: /etc/pmacct/
            - name: nfacctd-config-gen-volume
              mountPath: /tmp/pmacct/
              readOnly: true
      containers:
        - name: nfacctd-worker
          image: pmacct/nfacctd:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: flowlogs
              protocol: UDP
              containerPort: 2055
            - name: bgp
              protocol: TCP
              containerPort: 179
          volumeMounts:
            - name: datahangar-config-volume
              mountPath: /etc/datahangar
              readOnly: true
            - name: nfacctd-config-volume
              mountPath: /etc/pmacct/
              readOnly: true
          resources:
            limits:
              cpu: 1500m
              memory: 1G
            requests:
              cpu: 500m
              memory: 256M
      volumes:
        - name: datahangar-config-volume
          configMap:
            name: datahangar-config-map
        - name: nfacctd-config-gen-volume
          configMap:
            name: nfacctd-config-gen-map
        - name: nfacctd-config-volume
          emptyDir: {}
