apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfacctd-workers
  namespace: datahangar-stack
  labels:
    app: nfacctd
spec:
  selector:
    matchLabels:
      app: nfacctd
  replicas: 1
  template:
    metadata:
      labels:
        app: nfacctd
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: nfacctd
      initContainers:
        - name: sfunnel
          image: ghcr.io/datahangar/sfunnel:0.0.6@sha256:be12287922d9b26ad3a77403957a6b1c4093a1e97dec44e0d2d3308a91596c03
          securityContext:
            privileged: false
            capabilities:
              add:
                - BPF
                - NET_ADMIN
                - SYS_ADMIN
          volumeMounts:
            - name: bpffs
              mountPath: /sys/fs/bpf
        - name: nfacctd-conf-generator
          image: ghcr.io/datahangar/init-conf-gen:0.0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka
                  key: username
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka
                  key: password
          command: ["sh", "-c", "python3 /tmp/pmacct/gen_nfacctd_conf.py"]
          volumeMounts:
            - name: datahangar-config-volume
              mountPath: /etc/datahangar
              readOnly: true
            - name: nfacctd-config-volume
              mountPath: /etc/pmacct/
            - name: nfacctd-config-gen-volume
              mountPath: /tmp/pmacct/
              readOnly: true
      containers:
        - name: nfacctd-worker
          image: pmacct/nfacctd:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: bgp
              protocol: TCP
              containerPort: 179
            - name: ipfix
              protocol: UDP
              containerPort: 4739
            - name: sflow
              protocol: UDP
              containerPort: 6343
            - name: netflow
              protocol: UDP
              containerPort: 2055
          volumeMounts:
            - name: datahangar-config-volume
              mountPath: /etc/datahangar
              readOnly: true
            - name: nfacctd-config-volume
              mountPath: /etc/pmacct/
              readOnly: true
          resources:
            limits:
              cpu: 1500m
              memory: 1G
            requests:
              cpu: 500m
              memory: 256M
      volumes:
        - name: bpffs
          hostPath:
            path: /sys/fs/bpf
        - name: datahangar-config-volume
          configMap:
            name: datahangar-config-map
        - name: nfacctd-config-gen-volume
          configMap:
            name: nfacctd-config-gen-map
        - name: nfacctd-config-volume
          emptyDir: {}
