kind: Service
apiVersion: v1
metadata:
  name: flowlogs-ingestor-internal
  namespace: datahangar-stack
spec:
  selector:
    app: nfacctd
  ports:
  - protocol: UDP
    port: 2111
    targetPort: 2111
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: flowlog-ingestor
  namespace: datahangar-stack
spec:
  selector:
    app: nfacctd
  ports:
  - protocol: UDP
    port: 2111
    targetPort: 2111
  externalTrafficPolicy: Local #Do not SNAT to the service!
  type: LoadBalancer
