kind: Service
apiVersion: v1
metadata:
  name: flowlogs-ingestor-internal
  namespace: datahangar-stack
spec:
  selector:
    app: nfacctd
  ports:
  - name: bgp
    protocol: TCP
    port: 179
    targetPort: 179
  - name: ipfix
    protocol: UDP
    port: 4739
    targetPort: 4739
  - name: sflow
    protocol: UDP
    port: 6343
    targetPort: 6343
  - name: netflow
    protocol: UDP
    port: 2055
    targetPort: 2055
  type: ClusterIP
  sessionAffinity: ClientIP
---
kind: Service
apiVersion: v1
metadata:
  name: flowlogs-ingestor
  namespace: datahangar-stack
spec:
  selector:
    app: nfacctd
  ports:
  - name: bgp
    protocol: TCP
    port: 179
    targetPort: 179
    #IPFIX, sFLOW and Netflow funneled through TCP/179
  type: LoadBalancer
  externalTrafficPolicy: Local #Do not SNAT to the service!
  sessionAffinity: ClientIP
