apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  annotations:
    generated: "true"
  disableNameSuffixHash: true
configMapGenerator:
  - name: nfacctd-config-gen-map
    namespace: datahangar-stack
    files:
      - files/nfacctd.conf.j2
      - files/librdkafka.conf.j2
      - files/gen_nfacctd_conf.py

resources:
  - 02-nfacctd.yaml
  - 03-service.yaml
