apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: postgresql
  name: postgres-headless-service
  namespace: datahangar-stack
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
