apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-turnilo-config-map
  namespace: datahangar-stack
data:
  config.yaml: |
    serverRoot: turnilo
    customization:
      timezones:
      - America/Juneau
      - America/Los_Angeles
      - America/Yellowknife
      - America/Phoenix
      - America/Denver
      - America/Mexico_City
      - America/Chicago
      - America/New_York
      - America/Argentina/Buenos_Aires
      - Etc/UTC
      - Asia/Jerusalem
      - Europe/Paris
      - Asia/Kathmandu
      - Asia/Hong_Kong
      - Asia/Seoul
      - Pacific/Guam
    clusters:
      - name: druid
        type: druid
        url: http://druid-cluster-routers:8088
        timeout: 40000
        sourceListScan: false #auto
        sourceListRefreshOnLoad: false
        sourceListRefreshInterval: 5000
        sourceReintrospectOnLoad: false
        sourceReintrospectInterval: 5000
        #introspectionStrategy: segment-metadata-fallback

    dataCubes:
      - name: networkFlows
        title: Network Flowlogs
        clusterName: druid
        source: networkFlows
        timeAttribute: __time

        refreshRule:
          rule: query

        defaultTimezone: Etc/UTC
        defaultDuration: P1D
        defaultSortMeasure: bytes
        defaultSelectedMeasures: []

        defaultPinnedDimensions: []
        introspection: autofill-all
        attributeOverrides:
        dimensions:
          - name: time
            title: Time
            kind: time
            formula: $__time

          - name: flow_data
            title: Flow data
            dimensions:
              - name: iface_in
                title: Iface In
                formula: $iface_in
                kind: number

              - name: iface_out
                title: Iface Out
                formula: $iface_out
                kind: number

              - name: ip_src
                title: Ip Src
                formula: $ip_src

              - name: ip_dst
                title: Ip Dst
                formula: $ip_dst

              - name: ip_proto
                title: Ip Proto
                formula: $ip_proto

              - name: tos
                title: Tos
                formula: $tos

              - name: port_src
                title: Port Src
                formula: $port_src
                kind: number

              - name: port_dst
                title: Port Dst
                formula: $port_dst
                kind: number

              - name: tcp_flags
                title: Tcp Flags
                formula: $tcp_flags

              - name: class
                title: Class
                formula: $class

          - name: kafka_group
            title: Ingestion info (Kafka)
            dimensions:
              - name: kafka.topic
                title: Topic
                formula: ${kafka.topic}

              - name: writer_id
                title: Writer Id
                formula: $writer_id

              - name: event_type
                title: Event Type
                formula: $event_type

              - name: kafka.timestamp
                title: Timestamp
                formula: ${kafka.timestamp}

              - name: timestamp_end
                title: Timestamp End
                formula: $timestamp_end

        measures:
          - name: packets
            title: Packets
            formula: $main.sum($packets)
            format: 0,0.0 a

          - name: bytes
            title: Bytes
            formula: $main.sum($bytes)
            format: 0,0.0 a
