apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: turnilo
  name: turnilo
  namespace: datahangar-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turnilo
  template:
    metadata:
      labels:
        app: turnilo
    spec:
      initContainers:
        - name: turnilo-conf-generator
          image: ghcr.io/datahangar/init-conf-gen:0.0.2
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "python3 /tmp/gen_turnilo_conf.py"]
          volumeMounts:
            - name: datahangar-config-volume
              mountPath: /etc/datahangar
              readOnly: true
            - name: turnilo-config-volume
              mountPath: /etc/turnilo/
            - name: turnilo-config-gen-volume
              mountPath: /tmp/
              readOnly: true
      containers:
        - image: ghcr.io/datahangar/turnilo:1.40.2-bookworm
          command: ["/bin/bash", "-c", "/app/bin/turnilo run-config /etc/turnilo/config.yaml"]
          imagePullPolicy: IfNotPresent
          name: turnilo
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: turnilo-config-volume
              mountPath: /etc/turnilo/
              readOnly: true
          resources:
            limits:
              cpu: 1500m
              memory: 1G
            requests:
              cpu: 500m
              memory: 256M
      volumes:
        - name: datahangar-config-volume
          configMap:
            name: datahangar-config-map
        - name: turnilo-config-gen-volume
          configMap:
            name: turnilo-config-gen-map
        - name: turnilo-config-volume
          emptyDir: {}
