apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: turnilo
  name: turnilo
  namespace: datahangar-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turnilo
  template:
    metadata:
      labels:
        app: turnilo
    spec:
      containers:
        - image: ghcr.io/datahangar/turnilo:1.40.2-bookworm
          command: ["/bin/bash", "-c", "python3 /tmp/conf/gen_turnilo_conf.py && /app/bin/turnilo run-config /turnilo_config.yaml"]
          imagePullPolicy: IfNotPresent
          name: turnilo
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: datahangar-config-volume
              mountPath: /etc/datahangar
              readOnly: true
            - name: datahangar-dataprofiles-config-volume
              mountPath: /etc/datahangar/data-profiles/
              readOnly: true
            - name: turnilo-config-volume
              mountPath: /tmp/conf
              readOnly: true
          resources:
            limits:
              cpu: 1500m
              memory: 1G
            requests:
              cpu: 500m
              memory: 256M
      volumes:
        - name: datahangar-config-volume
          configMap:
            name: datahangar-config-map
        - name: datahangar-dataprofiles-config-volume
          configMap:
            name: datahangar-dataprofiles-config-map
        - name: turnilo-config-volume
          configMap:
            name: turnilo-config-map
