apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  annotations:
    generated: "true"
  disableNameSuffixHash: true
configMapGenerator:
  - name: turnilo-config-map
    namespace: datahangar-stack
    files:
      - files/gen_turnilo_conf.py
      - files/turnilo_conf.yaml.j2
resources:
  - 02-turnilo.yaml
  - 03-service.yaml
