apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend-service
  namespace: datahangar-stack
spec:
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: datahangar-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: ghcr.io/datahangar/frontend:0.0.3
          imagePullPolicy: IfNotPresent
          name: frontend
          command: ["sh", "-c", ". /tmp/gen_htpasswd.sh && nginx -g \"daemon off;\""]
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          volumeMounts:
            - name: frontend-volume
              mountPath: /etc/nginx/conf.d/
              readOnly: true
            - name: frontend-users-volume
              mountPath: /tmp/users.yaml
              subPath: users.yaml
              readOnly: true
            - name: frontend-scripts-volume
              mountPath: /tmp/gen_htpasswd.sh
              readOnly: false
              subPath: gen_htpasswd.sh
            - name: frontend-certs-volume
              mountPath: /etc/nginx/certs/
              readOnly: true
          resources:
            limits:
              cpu: 1000m
              memory: 512G
            requests:
              cpu: 250m
              memory: 128M
      volumes:
        - name: frontend-scripts-volume
          configMap:
            name: frontend-scripts-config-map
        - name: frontend-certs-volume
          secret:
            secretName: frontend-certs-secret
        - name: frontend-volume
          configMap:
            name: frontend-config-map
        - name: frontend-users-volume
          secret:
            secretName: datahangar-users-secret
