apiVersion: batch/v1
kind: Job
metadata:
  name: druid-load-supervisor-tasks
  labels:
    app: load-supervisor-tasks
  namespace: datahangar-stack
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: druid-load-supervisor-tasks
    spec:
      containers:
      - image: ghcr.io/datahangar/init-conf-gen:0.0.2
        imagePullPolicy: IfNotPresent
        env:
          - name: KAFKA_USERNAME
            valueFrom:
              secretKeyRef:
                name: kafka
                key: username
          - name: KAFKA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kafka
                key: password
        command: ["bash", "-c", "python3 -u /tmp/submit_kafka_ingest_tasks.py"]
        volumeMounts:
          - name: datahangar-config-volume
            mountPath: /etc/datahangar
            readOnly: true
          - name: druid-supervisor-ingestor-tasks
            mountPath: /tmp/
            readOnly: true
        name: druid-load-supervisor-tasks
      restartPolicy: Never
      volumes:
        - name: datahangar-config-volume
          configMap:
            name: datahangar-config-map
        - name: druid-supervisor-ingestor-tasks
          configMap:
            name: druid-supervisor-tasks-config-map
