apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-rbac.yaml
  - 01-pvc.yaml
  - 02-conf.yaml
  - 03-services.yaml
  - 04-druid.yaml
  - 05-conf-job-supervisor-task.yaml
  - 06-job-create-supervisor-task.yaml
