apiVersion: v1
kind: ConfigMap
metadata:
  name: druid-historicals-config-map
  namespace: stack
data:
  jvm.config: |-
    -server
    -Xms512m
    -Xmx2g
    -XX:MaxDirectMemorySize=4g
    -XX:+ExitOnOutOfMemoryError
    -Duser.timezone=UTC
    -Dfile.encoding=UTF-8
    -Djava.io.tmpdir=var/tmp
    -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
  main.config: |-
    org.apache.druid.cli.Main server historical
  runtime.properties: |-
    #Role
    druid.service=druid/historical

    # Processing threads and buffers
    #druid.processing.buffer.sizeBytes=50000000
    #druid.processing.numMergeBuffers=4
    #druid.processing.numThreads=2

    # Segment storage
    druid.segmentCache.locations=[{"path":"var/druid/segment-cache","maxSize":"300g"}]

    # Query cache
    druid.historical.cache.useCache=true
    druid.historical.cache.populateCache=true
    druid.cache.type=caffeine
    druid.cache.sizeInBytes=256MiB
