apiVersion: v1
kind: ConfigMap
metadata:
  name: druid-middlemanagers-config-map
  namespace: datahangar-stack
data:
  jvm.config: |-
    -server
    -Xms128m
    -Xmx256m
    -XX:MaxDirectMemorySize=512m
    -XX:+ExitOnOutOfMemoryError
    -Duser.timezone=UTC
    -Dfile.encoding=UTF-8
    -Djava.io.tmpdir=var/tmp
    -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
  main.config: |-
    org.apache.druid.cli.Main server middleManager
  runtime.properties: |-
    #Role
    druid.service=druid/middleManager
    druid.worker.capacity=4
    druid.worker.baseTaskDirs=[\"var/druid/task\"]

    # Task launch parameters
    druid.indexer.runner.javaOptsArray=[ "-server", "-Xms256m", "-Xmx512m", "-XX:MaxDirectMemorySize=1g", "-Duser.timezone=UTC", "-Dfile.encoding=UTF-8", "-XX:+ExitOnOutOfMemoryError", "-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager" ]

    #Processing specifics
    druid.indexer.fork.property.druid.processing.numThreads=1
    druid.indexer.fork.property.druid.processing.numMergeBuffers=2
    druid.indexer.fork.property.druid.processing.buffer.sizeBytes=100MiB

    # Hadoop indexing
    druid.indexer.task.hadoopWorkingPath=var/druid/hadoop-tmp
