apiVersion: v1
kind: Secret
metadata:
  name: clickhouse
  namespace: datahangar-stack
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/component: clickhouse
type: Opaque
data:
  admin-password: "Rm9vbGlzaFBhc3N3b3Jk"
