apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse
  namespace: datahangar-stack
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/component: clickhouse
data:
  00_default_overrides.xml: |
    <clickhouse>
      <!-- Autodiscovery -->
      <allow_experimental_cluster_discovery>1</allow_experimental_cluster_discovery>
      <!-- Macros -->
      <macros>
        <shard from_env="CLICKHOUSE_SHARD_ID"></shard>
        <replica from_env="CLICKHOUSE_REPLICA_ID"></replica>
        <layer>clickhouse</layer>
      </macros>
      <!-- Log Level -->
      <logger>
        <level>debug</level>
      </logger>
      <!-- cluster configuration -->
      <remote_servers>
        <stack>
          <discovery>
            <path>/clickhouse/discovery/stack</path>
            <shard from_env="CLICKHOUSE_SHARD_ID"/>
          </discovery>
        </stack>
      </remote_servers>
      <zookeeper>
        <node>
          <host>zookeeper-headless-service</host>
          <port>2181</port>
        </node>
      </zookeeper>
    </clickhouse>
