apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-ingestion-task-config-map
  namespace: datahangar-stack
data:
  networkFlows_script.sql: |
    CREATE TABLE IF NOT EXISTS networkFlows
    (
        `event_type` String,
        `class` String,
        `iface_in` UInt32,
        `iface_out` UInt32,
        `ip_src` String,
        `ip_dst` String,
        `port_src` UInt16,
        `port_dst` UInt16,
        `tcp_flags` String,
        `tos` UInt16,
        `timestamp_start` DateTime64,
        `timestamp_end` DateTime64,
        `packets` UInt64,
        `bytes` UInt64,
        `writer_id` String
    )
    ENGINE = MergeTree
    ORDER BY (ip_src, ip_dst);

    CREATE TABLE IF NOT EXISTS networkFlowsKafkaIngest (
        event_type String,
        class String,
        iface_in UInt32,
        iface_out UInt32,
        ip_src String,
        ip_dst String,
        port_src UInt16,
        port_dst UInt16,
        tcp_flags String,
        tos UInt16,
        timestamp_start DateTime64,
        timestamp_end DateTime64,
        packets UInt64,
        bytes UInt64,
        writer_id String
    )
    ENGINE = Kafka
    SETTINGS kafka_broker_list = 'kafka-headless-service:9093',
           kafka_topic_list = 'flowlogs',
           kafka_group_name = 'group1',
           kafka_format = 'JSON',
           kafka_max_block_size = 1048576;

    CREATE MATERIALIZED VIEW IF NOT EXISTS networkFlowsQueueMv TO networkFlows AS SELECT event_type, class, iface_in, iface_out, ip_src, ip_dst, port_src, port_dst, tcp_flags, tos, timestamp_start, timestamp_end, packets, bytes, writer_id FROM networkFlowsKafkaIngest;
