apiVersion: batch/v1
kind: Job
metadata:
  name: clickhouse-load-ingestion-task
  labels:
    app: load-ingestion-task
  namespace: datahangar-stack
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: clickhouse-load-ingestion-task
    spec:
      containers:
      - image: clickhouse/clickhouse-server
        imagePullPolicy: IfNotPresent
        env:
          - name: CLICKHOUSE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: clickhouse
                key: admin-password
        command: ["/bin/bash"]
        args: ["-c", "apt-get update && apt-get install -y python3 python3-jinja2 python3-pip && pip3 install pyyaml && python3 /tmp/gen/generate_ingest_tables.py"]
        volumeMounts:
          - name: datahangar-config-volume
            mountPath: /etc/datahangar
            readOnly: true
          - name: clickhouse-ingestion-sql-gen-volume
            mountPath: /tmp/gen
            readOnly: true
        name: clickhouse-load-ingestion-task
      restartPolicy: Never
      volumes:
        - name: datahangar-config-volume
          configMap:
            name: datahangar-config-map
        - name: clickhouse-ingestion-sql-gen-volume
          configMap:
            name: clickhouse-ingestion-sql-gen-config-map
