apiVersion: batch/v1
kind: Job
metadata:
  name: clickhouse-load-ingestion-task
  labels:
    app: load-ingestion-task
  namespace: datahangar-stack
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: clickhouse-load-ingestion-task
    spec:
      containers:
      - image: clickhouse/clickhouse-server
        env:
          - name: CLICKHOUSE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: clickhouse
                key: admin-password
        command: ["/bin/bash"]
        args: ["-c", "apt-get update && apt-get install -y python3 python3-jinja2 && python3 /tmp/conf/generate_ingest_tables.py"]
        volumeMounts:
          - name: datahangar-config-volume
            mountPath: /etc/datahangar
            readOnly: true
          - name: datahangar-dataprofiles-config-volume
            mountPath: /etc/datahangar/data-profiles/
            readOnly: true
          - name: gen-ingestion-sql-config-volume
            mountPath: /tmp/conf
            readOnly: true
        imagePullPolicy: IfNotPresent
        name: clickhouse-load-ingestion-task
      restartPolicy: Never
      volumes:
        - name: datahangar-config-volume
          configMap:
            name: datahangar-config-map
        - name: datahangar-dataprofiles-config-volume
          configMap:
            name: datahangar-dataprofiles-config-map
        - name: gen-ingestion-sql-config-volume
          configMap:
            name: gen-ingestion-sql-config-map
