apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  annotations:
    generated: "true"
  disableNameSuffixHash: true
configMapGenerator:
  - name: clickhouse-ingestion-sql-gen-config-map
    namespace: datahangar-stack
    files:
      - files/create_tables_script.sql.j2
      - files/generate_ingest_tables.py

resources:
  - 00-rbac.yaml
  - 00-secrets-clickhouse.yaml
  - 01-services.yaml
  - 02-pvc.yaml
  - 03-conf-clickhouse.yaml
  - 03-conf-scripts-clickhouse.yaml
  - 04-clickhouse.yaml
  - 06-job-ingestion-task.yaml
