name: ci

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  basic:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        k8s_version: [v1.27.13, v1.28.9, v1.29.4]
    env:
      KCTL: "minikube kubectl -- "
    steps:
      #Clone datahangar
      - name: Checkout datahangar
        uses: actions/checkout@v4
        with:
          path: datahangar

      - name: Install python3 dependencies
        run: |
         pip install -r datahangar/tools/requirements.txt

      #Start minikube
      - name: "Start minikube - K8s ${{matrix.k8s_version}}"
        id: minikube
        uses: medyagh/setup-minikube@latest
        with:
          kubernetes-version: ${{matrix.k8s_version}}
          cpus: 'max'
          memory: 12G

      #Deploy stack
      - name: Deploy DataHangar stack
        run: |
          cd /home/runner/work/datahangar/datahangar/datahangar
          tools/dhctl.py -v deploy dev

      #Check stack health
      - name: Check health status of the DataHangar stack
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 3
          max_attempts: 40
          retry_wait_seconds: 15
          shell: bash
          command: /home/runner/work/datahangar/datahangar/datahangar/tools/dhctl.py status dev -p /home/runner/work/datahangar/datahangar/datahangar/
